spring.application.name=tracker
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}
# spring.data.mongodb.uri=mongodb://localhost:27017/finance_tracker
spring.data.mongodb.uri=${MONGODB_URI}
