spring.application.name=tracker
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}
# spring.data.mongodb.uri=mongodb://localhost:27017/finance_tracker
spring.data.mongodb.uri=${MONGODB_URI}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}
